version: "3"
services:
  php:
    build: /php
    networks:
      - isolated-server
    volumes:
      - "./src:/var/www/html"
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=site
    volumes:
      - "./mysql/dump:/docker-entrypoint-initdb.d"
    networks:
      - isolated-server
  serv:
    image: nginx
    ports:
      - "80:80"
    networks:
      - isolated-server
    volumes:
      - "./src:/var/www/html"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
      - mysql
networks:
  isolated-server:
    driver: bridge